#!/usr/bin/env node
/**
 * Aurelius Dashboard — CSS build script
 * Concatenates CSS partials into a single bundle for production.
 *
 * Usage:
 *   node build.js            → bundle (unminified, with section headers)
 *   node build.js --minify   → bundle + minify (used by Netlify)
 *   node build.js --watch    → watch partials and rebuild on change
 *   node build.js --minify --watch
 */

const fs   = require('fs');
const path = require('path');

// ── Config ───────────────────────────────────────────────────────────────────

const ROOT = __dirname;

const PARTIALS = [
  // Theme — design tokens (must load before everything else)
  'src/styles/theme/fonts.css',
  'src/styles/theme/brand.css',
  'src/styles/theme/colours.css',
  'src/styles/theme/typography.css',
  'src/styles/theme/animations.css',
  'src/styles/theme/osui-bridge.css',
  // Base — resets, defaults, scrollbar
  'src/styles/base/base.css',
  // Layout — shell, topbar, sidebar, grids
  'src/styles/layout/layout.css',
  // Modules — reusable UI components
  'src/styles/modules/brand.css',
  'src/styles/modules/navigation.css',
  'src/styles/modules/theme-toggle.css',
  'src/styles/modules/buttons.css',
  'src/styles/modules/cards.css',
  'src/styles/modules/charts.css',
  'src/styles/modules/tables.css',
  'src/styles/modules/progress.css',
  'src/styles/modules/activity.css',
  'src/styles/modules/documents.css',
  'src/styles/modules/footer.css',
  'src/styles/modules/advisor-card.css',
  'src/styles/modules/ob-cta.css',
  'src/styles/modules/breadcrumb.css',
  'src/styles/modules/page-header.css',
  'src/styles/modules/contact.css',
  'src/styles/modules/details.css',
  'src/styles/modules/forms.css',
  'src/styles/modules/drawers.css',
  'src/styles/modules/chat.css',
  'src/styles/modules/adviser.css',
  'src/styles/modules/user-menu.css',
  'src/styles/modules/notifications.css',
  'src/styles/modules/feedback.css',
  'src/styles/modules/add-investment.css',
  'src/styles/modules/onboarding.css',
  // State — is-* classes
  'src/styles/state/state.css',
  // Pages — page-specific overrides
  'src/styles/pages/pages.css',
].map(f => path.join(ROOT, f));

const OUTPUT  = path.join(ROOT, 'src', 'styles', 'bundle.css');
const MINIFY  = process.argv.includes('--minify');
const WATCH   = process.argv.includes('--watch');

// ── Minifier ─────────────────────────────────────────────────────────────────

function minifyCSS(css) {
  return css
    // Remove block comments
    .replace(/\/\*[\s\S]*?\*\//g, '')
    // Collapse all whitespace runs to a single space
    .replace(/\s+/g, ' ')
    // Strip spaces around structural characters
    .replace(/\s*([{}:;,>~+])\s*/g, '$1')
    // Remove trailing semicolons before closing brace
    .replace(/;}/g, '}')
    .trim();
}

// ── Bundler ──────────────────────────────────────────────────────────────────

function bundle() {
  const start = Date.now();

  let missing = false;
  const sections = PARTIALS.map(filePath => {
    if (!fs.existsSync(filePath)) {
      console.error(`✗ Missing partial: ${path.relative(ROOT, filePath)}`);
      missing = true;
      return '';
    }
    const src = fs.readFileSync(filePath, 'utf8');
    if (MINIFY) return src;
    const name = path.relative(ROOT, filePath).replace(/\\/g, '/');
    const bar  = '─'.repeat(60 - name.length);
    return `/* ── ${name} ${bar} */\n${src}`;
  });

  if (missing) {
    process.exitCode = 1;
    return;
  }

  const separator = MINIFY ? '' : '\n\n';
  let output = sections.join(separator);

  if (MINIFY) {
    output = minifyCSS(output);
  }

  // Add a generation header (only when not minifying, to preserve readability)
  if (!MINIFY) {
    const ts = new Date().toISOString();
    output = `/* Generated by build.js — ${ts} — DO NOT EDIT */\n\n${output}`;
  }

  fs.writeFileSync(OUTPUT, output, 'utf8');

  const elapsed  = Date.now() - start;
  const bytes    = Buffer.byteLength(output, 'utf8');
  const kb       = (bytes / 1024).toFixed(1);
  const modeTag  = MINIFY ? ' (minified)' : '';
  const outRel   = path.relative(ROOT, OUTPUT).replace(/\\/g, '/');

  console.log(`✓  ${outRel}  ${kb} kB${modeTag}  [${elapsed}ms]`);
}

// ── Watch mode ───────────────────────────────────────────────────────────────

function watch() {
  console.log('Watching CSS partials for changes…\n');

  const watchers = PARTIALS.map(filePath => {
    const rel = path.relative(ROOT, filePath).replace(/\\/g, '/');

    return fs.watch(filePath, eventType => {
      if (eventType === 'change') {
        process.stdout.write(`  changed → ${rel}\n  `);
        bundle();
      }
    });
  });

  // Graceful shutdown
  ['SIGINT', 'SIGTERM'].forEach(sig => {
    process.once(sig, () => {
      watchers.forEach(w => w.close());
      console.log('\nWatcher stopped.');
      process.exit(0);
    });
  });
}

// ── Entry ────────────────────────────────────────────────────────────────────

bundle();

if (WATCH) watch();
